endpoints.health.enabled: true

hazelcast.max.no.heartbeat.seconds: 6

admin.application.url: http://104.197.139.214:30004/admin/companies

news.application.url: http://104.197.139.214:30005/news/twitter
