apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: default
  labels:
    name: config-server-service
spec:
  type: NodePort
  ports:
  - port: 8001
    nodePort: 30002
    targetPort: 8001
    protocol: TCP

  selector:
    name: config-server
    deploymentType: BLUE