apiVersion: v1
kind: Namespace
metadata:
  name: ru-deployment
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: config-server
  namespace: ru-deployment
  labels:
    name: config-server
    service: config-server-service
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      name: config-server
      type: backend
  strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
  template:
    metadata:
      labels:
        name: config-server
        type: backend
    spec:
      containers:
      - name: config-server
        image: nisumpk/config_server
        ports:
        - containerPort: 8001
        env:
        - name: GIT_CONFIG_DIRECTORY
          value: "-Dspring.cloud.config.server.git.searchPaths: cloudstack"
        - name: SERVER_PORT
          value: "-Dserver.port=8001"
        - name: DISCOVERY_SERVER_URL
          value: "-Deureka.client.serviceUrl.defaultZone=http://discovery-server-service.ru-deployment.svc.cluster.local:7001/eureka/"
        command: ["java"]
        args: ["$(SERVER_PORT)", "$(DISCOVERY_SERVER_URL)", "$(GIT_CONFIG_DIRECTORY)", "-Deureka.instance.preferIpAddress=true", "-Deureka.instance.ipAddress=config-server-service", "-jar", "/usr/src/config-server-SNAPSHOT.jar"]
        readinessProbe:
          tcpSocket:
            port: 8001
           # host: 127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8001
          #  host: 127.0.0.1
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: ru-deployment
  labels:
    name: config-server-service
spec:
  type: NodePort
  ports:
  - port: 8001
    nodePort: 30051
    targetPort: 8001
    protocol: TCP

  selector:
    name: config-server
