apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: config-server-virtualservice
  namespace: canary
spec:
  hosts:
  - config-server
  http:
  - route:
    - destination:
        host: config-server
        subset: config-server-v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: config-server-dr
  namespace: canary
spec:
  host: config-server
  subsets:
  - name: config-server-v1
    labels:
      version: config-server-v1
