server.port: 8001

spring:
  application.name: config-server
  cloud.config.server.git.uri: https://github.com/fqadeer-nisum-com/DevOpsPOC-config.git
  cloud.config.server.git.searchPaths: cloudstack

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
