apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ include "config-server.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    targetPort: {{ .Values.service.port }}
    name: http
  selector:
    app: {{ include "config-server.name" . }}
